### ISSUE TITLE
皮肤预览，容器大小发生改变，如果用了布局，组件位置会发生位移

### ISSUE THREAD

**Issue by cruelsheep** [egret-labs/egret-ui-editor-opensource#102]

**Comment by fpsqdb** [comment]
@cruelsheep  能提供示例和重现步骤吗

**Comment by cruelsheep** [comment]
![image](https://user-images.githubusercontent.com/67779257/89628944-9baf2c80-d8cf-11ea-8e9d-5f27615e2e62.png)
![image](https://user-images.githubusercontent.com/67779257/89628978-a79aee80-d8cf-11ea-9d1e-5e959ae55a62.png)
