### ISSUE TITLE
新建皮肤添加组件保存后，切换动画后，皮肤又恢复到没添加组件前得情况

### ISSUE THREAD

**Issue by cruelsheep** [egret-labs/egret-ui-editor-opensource#107]
![image](https://user-images.githubusercontent.com/67779257/90002786-b74a7680-dcc5-11ea-885f-f37d5992f684.png)
已保存
![image](https://user-images.githubusercontent.com/67779257/90002837-ccbfa080-dcc5-11ea-949b-0c2c59574e08.png)点击动画之后又变成了可保存提示且添加得组件全没了

**Comment by fpsqdb** [comment]
Editor版本号是多少？请升级到最新版v1.11.1

**Comment by cruelsheep** [comment]
嗯，更新完好了
