### ISSUE TITLE
显示Bug，在图层处改边属性保存，然后直接却换至源码，出现文件未保存提示（*号），如果添加新改动的话，这个提示符会一直存在

### ISSUE THREAD

**Issue by cruelsheep** [egret-labs/egret-ui-editor-opensource#108]

**Comment by fpsqdb** [comment]
fixed in [434a82b](https://github.com/egret-labs/egret-ui-editor-opensource/commit/434a82b8576d4082e338d0f432f743fe089ebbdd)
