### ISSUE TITLE
eui命令在mac平台如何使用？

### ISSUE THREAD

**Issue by zt5** [egret-labs/egret-ui-editor-opensource#125]
[文档地址](https://docs.egret.com/uieditor/docs/uieditor/manual/install#%E5%90%AF%E5%8A%A8-egret-ui-editor) 这里面 的eui命令在windows平台可以使用 mac平台提示 command not found: eui

**Comment by zt5** [comment]
egret run 或 build之类的命令是可以使用的

**Comment by fpsqdb** [comment]
@zt5 mac下需要手动安装shell命令，打开UI Editor 菜单栏：文件->安装 shell 命令
