### ISSUE TITLE
打开老项目卡死

### ISSUE THREAD

**Issue by zsytssk** [egret-labs/egret-ui-editor-opensource#15]
![TIM截图20191218161953](https://user-images.githubusercontent.com/2304648/71068715-40022880-21b2-11ea-829d-cca88d580aee.png)

**Comment by runinspring** [comment]
能提供一个简单的复现demo吗

**Comment by runinspring** [comment]
能提供一个简单的复现demo吗

**Comment by zsytssk** [comment]
公司的老项目 不能打包给你；

**Comment by donhwa** [comment]
> 
> 
> 公司的老项目 不能打包给你；你看那截图上的报错信息，又没关系；

哈哈，你这语气，作为项目外的人，我都看着不舒服。

**Comment by WanderWang** [comment]
请问是否可以尝试提取出一个最小的可重现demo呢？ @zsytssk

**Comment by WanderWang** [comment]
您好，有其他开发者反馈了类似的问题，我们已经在 1.7.1 版本中修复了此问题
