### ISSUE TITLE
Egret UI Editor "Failed to get the engine list, try to restore the engine enviroment variable to ensure that the 'egret verions' command can be executed normally.

### ISSUE THREAD

**Issue by jinoojinoo** [egret-labs/egret-ui-editor-opensource#151]
egret verions??
version??

where does it fix egret "verions"?? 

![1111](https://user-images.githubusercontent.com/33148747/144011714-f6cb45ff-4729-4a1b-811f-12885a137c17.png)

**Comment by fpsqdb** [comment]
Please check if `egret versions` can be run on the command line.
```
PS C:\Users\egret> egret versions
Egret Engine 5.3.10  C:\Users\egret\AppData\Roaming\Egret\engine\5.3.10
Egret Engine 5.3.8  E:\Downloads\egret-core-fastgame
Egret Engine 5.3.7  C:\Users\egret\AppData\Roaming\Egret\engine\5.3.7
Egret Engine 5.3.5  C:\Users\egret\AppData\Roaming\Egret\engine\5.3.5
Egret Engine 5.2.33  C:\Users\egret\AppData\Roaming\Egret\engine\5.2.33
Egret Engine 5.2.27  C:\Users\egret\AppData\Roaming\Egret\engine\5.2.27
PS C:\Users\egret>
```
If it does not work, you may need to reinstall [Egret Launcher](https://docs.egret.com/engine)

**Comment by jinoojinoo** [comment]
thank you reply 
but same....
do you know filename to get egret ui editor versions ??

**Comment by jinoojinoo** [comment]
egret versions
openssl config failed: error:25078067:DSO support routines:win32_load:could not load the shared library
....
....

installed "Win64OpenSSL-1_1_1L" (Win64OpenSSL-3_0_0 have other issue)

solved.
Thany you.
