### ISSUE TITLE
“获取引擎列表失败，请尝试恢复引擎环境变量以保证”

### ISSUE THREAD

**Issue by Jarod-Xie** [egret-labs/egret-ui-editor-opensource#20]
使用1.6.0版本：打开一个eui项目，提示“获取引擎列表失败，请尝试恢复引擎环境变量以保证”。我的eui项目使用的引擎版本是5.2.31.引擎目录为了不占用c盘空间被我换到了D:\Program Files (x86)\Egret\engine\5.2.31。

**Comment by fpsqdb** [comment]
@Jarod-Xie 在命令行里运行`egret versions`, 看下有没有5.2.31

**Comment by sxd1140** [comment]
你应该是装的`EgretLauncher-insider`.
换官网下的 `EgretLauncher` 就好了.

**Comment by Jarod-Xie** [comment]
> 你应该是装的`EgretLauncher-insider`.
> 换官网下的 `EgretLauncher` 就好了.
重新下载最新版本安装了，的确好了，感谢~

**Comment by Jarod-Xie** [comment]
@sxd1140 @fpsqdb 下了官网最新的egret launcher，的确好了。谢谢
