### ISSUE TITLE
添加右键复制节点 id:type

### ISSUE THREAD

**Issue by zsytssk** [egret-labs/egret-ui-editor-opensource#36]
老编辑中的 复制id功能 id:eui.Label 这样的功能

**Comment by fpsqdb** [comment]
@zsytssk 是图层右键->复制自定义 吗?

![Annotation 2020-02-20 105025](https://user-images.githubusercontent.com/6482819/74896574-91f04600-53cf-11ea-95ac-95b8819d5c9f.png)

**Comment by zsytssk** [comment]
是的
