### ISSUE TITLE
算是新需求吧。egret wing中有的：能方便切换exml中的元素的隐藏显示状态的开关

### ISSUE THREAD

**Issue by Jarod-Xie** [egret-labs/egret-ui-editor-opensource#41]
![image](https://user-images.githubusercontent.com/27668637/76481713-3c96da00-644d-11ea-86d7-831f5a028737.png)
在egret wing中元素图层的右侧会有显示或者隐藏图层的开关，很方便，能不能加上。
目前想要显示或隐藏图层的话，好像只能在右侧的所有属性中去设置，并且一旦隐藏，改图层的所有属性栏会清空，想要再次显示就只能去代码里改，很不方便。

**Comment by TaoSiJun** [comment]
在egret wing中编辑exml，图层界面会有2个按钮，显示/隐藏这2个功能，在egret ui editor中希望能加上。

**Comment by sz928** [comment]
这个功能太重要了，不然老项目在 新的边编辑器没有办法编辑

**Comment by fpsqdb** [comment]
这是一个bug，再下一个版本1.8.0中会修复，参考 #38
