### ISSUE TITLE
can't find file which type of .res.json in sub folder from "/resource"

### ISSUE THREAD

**Issue by PotentialSteffan** [egret-labs/egret-ui-editor-opensource#45]

**Comment by fpsqdb** [comment]
I can't reproduce. Please provide more information: reproduction steps, screenshots, and reproduction of demo project is much better, Thanks.

**Comment by PotentialSteffan** [comment]
[EuiEditor_bugReproduce_demo.zip](https://github.com/egret-labs/egret-ui-editor-opensource/files/4464098/EuiEditor_bugReproduce_demo.zip)

file at "resource/assets/demoDir/demo.res.json" can not be  display in resource manager
