### ISSUE TITLE
1.8.0版本任意点击顶部设计 动画 预览 源码 会出现卡死

### ISSUE THREAD

**Issue by sunsnail0** [egret-labs/egret-ui-editor-opensource#46]
1.8.0版本任意点击顶部设计 动画 预览 源码 会出现卡死 复现率100%
win10 1909 2020年3月份版本

**Comment by fpsqdb** [comment]
@sunsnail0 我这无法重现，新建的eui项目会卡吗，能否提供一个重现的demo？

**Comment by fpsqdb** [comment]
请更新到最新版，该问题在1.8.1中已经修复
