### ISSUE TITLE
添加非resource文件夹支持

### ISSUE THREAD

**Issue by innocentjulie** [egret-labs/egret-ui-editor-opensource#48]
项目resource文件夹是由 resource_release发布而来，所有的源文件都是在resource_release文件夹中，能不能指定相应的源文件夹，而不是直接编辑resource文件夹下的皮肤资源

**Comment by fpsqdb** [comment]
如果要更改默认`resource`文件夹为`resource_release`，需要将`wingProperties.json`中配置的`resource`路径改为`resource_release`

![20200409143707](https://user-images.githubusercontent.com/6482819/78865378-14ac8d80-7a70-11ea-9883-d816ad4b3d6c.png)

同样需要将`default.thm.json`中配置的`resource`路径改为`resource_release`

![QQ20200409143748](https://user-images.githubusercontent.com/6482819/78865622-808ef600-7a70-11ea-8a1d-5a80e6f0cdc1.png)

**Comment by innocentjulie** [comment]
> 如果要更改默认`resource`文件夹为`resource_release`，需要将`wingProperties.json`中配置的`resource`路径改为`resource_release`
> 
> ![20200409143707](https://user-images.githubusercontent.com/6482819/78865378-14ac8d80-7a70-11ea-9883-d816ad4b3d6c.png)
> 
> 同样需要将`default.thm.json`中配置的`resource`路径改为`resource_release`
> 
> ![QQ20200409143748](https://user-images.githubusercontent.com/6482819/78865622-808ef600-7a70-11ea-8a1d-5a80e6f0cdc1.png)
你这个并不能解决问题，我们的现在就是这样，用UI editor并不能打开相应的目录，
![image](https://user-images.githubusercontent.com/1212207/79100831-e8f41500-7d99-11ea-8098-683273219d77.png)

**Comment by innocentjulie** [comment]
![image](https://user-images.githubusercontent.com/1212207/79100848-f3161380-7d99-11ea-95ba-1f241a729469.png)

**Comment by innocentjulie** [comment]
![image](https://user-images.githubusercontent.com/1212207/79100898-0de88800-7d9a-11ea-8af1-dbc89ce3c8c7.png)
什么内容文件夹都没有，

**Comment by fpsqdb** [comment]
@innocentjulie 打开的时候应用顶部有没有悬浮提示信息？打开菜单->帮助->切换开发者工具看下有没有报错

**Comment by innocentjulie** [comment]
资源管理器里面默认就直接显示了resource文件夹，但是我并不想编辑这个文件夹啊，我要编辑release文件夹下的资源啊

**Comment by fpsqdb** [comment]
`egretProperties.json`也需要修改一下
![QQ截图20200415101821](https://user-images.githubusercontent.com/6482819/79291942-8a967600-7f02-11ea-806e-45b689774385.png)

可以参考这个示例
[eui_test.zip](https://github.com/egret-labs/egret-ui-editor-opensource/files/4478777/eui_test.zip)

**Comment by innocentjulie** [comment]
> `egretProperties.json`也需要修改一下
> ![QQ截图20200415101821](https://user-images.githubusercontent.com/6482819/79291942-8a967600-7f02-11ea-806e-45b689774385.png)
> 
> 可以参考这个示例
> [eui_test.zip](https://github.com/egret-labs/egret-ui-editor-opensource/files/4478777/eui_test.zip)

我试下

**Comment by innocentjulie** [comment]
为啥我看不到图片，你这里的resource_release文件夹和resource文件夹是怎么来的，怎么没看到项目里面的发布文件夹，
![image](https://user-images.githubusercontent.com/1212207/81151976-16586b00-8fb4-11ea-8c01-bb9d03208ff2.png)，这里的发布json没找到，
还有个疑问，就是比如我的原始编辑用的的文件夹为resource/文件夹，然后使用resdepot发布，发布成的文件夹为resource_publish文件夹，那么我要执行egret publish发布之后，怎么release文件夹里面的是resource文件夹下的资源，而并不是resource_publish文件夹下的资源？明白么，不知道官方建议是应该怎么用的呢？有点疑惑

**Comment by runinspring** [comment]
resdepot 这是一个独立的工具，你文件夹叫 a，发布后就叫 a_publish。你可以把原始资源放到一个文件夹，发布后再拷贝到 resource 里
