### ISSUE TITLE
编辑皮肤时位置错误

### ISSUE THREAD

**Issue by sxd1140** [egret-labs/egret-ui-editor-opensource#6]
运行时正常
`wing 4.1.6`
`egret ui editor 1.5.0`
[wing-bug.zip](https://github.com/egret-labs/egret-ui-editor-opensource/files/3930029/wing-bug.zip)

**Comment by WanderWang** [comment]
感谢反馈，可以描述的更清晰一些么？

**Comment by sxd1140** [comment]
在编辑器里显示:
![1](https://user-images.githubusercontent.com/541212/70308510-646f1400-1846-11ea-942f-cd72cf67580a.png)

实际运行显示:
![2](https://user-images.githubusercontent.com/541212/70308527-6cc74f00-1846-11ea-82a3-e65b3b858063.png)


实际运行是对的.
显示不对的那个类 ex.Group 只是重写了`left`的`setter` 而皮肤内甚至都没有设置`left`.
注释掉 `set left` 就正常.

**Comment by WanderWang** [comment]
非常感谢！！
