### ISSUE TITLE
README 中反复提到的 Egret Coder 插件在哪里可以下载?

### ISSUE THREAD

**Issue by PotentialSteffan** [egret-labs/egret-ui-editor-opensource#62]

**Comment by fpsqdb** [comment]
[https://docs.egret.com/engine/docs/installation/installation-plugin](https://docs.egret.com/engine/docs/installation/installation-plugin)

**Comment by PotentialSteffan** [comment]
谢谢，不过现在项目用cocos creator了，加油！希望以后的项目有机会再使用egret。
