### ISSUE TITLE
git切分支后重新打开项目,EUI 项目设置报错

### ISSUE THREAD

**Issue by PotentialSteffan** [egret-labs/egret-ui-editor-opensource#65]
![image](https://user-images.githubusercontent.com/24876673/82788660-6d5aad00-9e9b-11ea-9469-342bf087de25.png)

**Comment by PotentialSteffan** [comment]
每次切分支都会报错,严重影响开发效率

**Comment by fpsqdb** [comment]
@PotentialSteffan 提示的/default.res.json在项目中吗？这个是提示项目resource目录下没有找到default.res.json文件。

**Comment by PotentialSteffan** [comment]
本地的项目没有default.res.json文件,取的其他名字

**Comment by fpsqdb** [comment]
建议在每个分支都正确配置，并将wingProperties.json和egretProperties.json包含到git一并提交。

**Comment by PotentialSteffan** [comment]
好的,非常感谢!
