### ISSUE TITLE
长按alt键,图示区域提示文字不停切换,建议长按不切换,仅点击切换

### ISSUE THREAD

**Issue by PotentialSteffan** [egret-labs/egret-ui-editor-opensource#72]
![image](https://user-images.githubusercontent.com/24876673/83723198-d945ce00-a670-11ea-8fbf-0764723b667b.png)

**Comment by fpsqdb** [comment]
已经修复 [4301b77](https://github.com/egret-labs/egret-ui-editor-opensource/commit/4301b77f9d7caf4cc80d528067cbc2b7134fa68c)
