### ISSUE TITLE
图层模块合组shift+alt+g快捷键无效,建议增加操作快捷键,提高开发效率

### ISSUE THREAD

**Issue by PotentialSteffan** [egret-labs/egret-ui-editor-opensource#73]
![image](https://user-images.githubusercontent.com/24876673/83723770-bff15180-a671-11ea-88fe-955133fe982d.png)

**Comment by fpsqdb** [comment]
合组和取消合组的快捷键默认是Ctrl+g和Ctrl+u，如果想更换为shift+alt+g可以通过文件->首选项->快捷键设置进行自定义
