### ISSUE TITLE
怎样修改compent的属性而不是改skin文件

### ISSUE THREAD

**Issue by yujiang** [egret-labs/egret-ui-editor-opensource#78]
比如在wing中双击一个按钮，可以修改这个按钮文字颜色，大小；以属性修改的形式放在exml中，对ButtonSkin.exml没有影响。
而在UI Edtiro双击一个按钮，直接修改ButtonSkin.exml，对其他所有按钮都造成了影响，这并非我想要的。

**Comment by fpsqdb** [comment]
可以通过右键->转换皮肤为内嵌皮肤，如果转换成内嵌皮肤双击后会直接编辑内嵌皮肤，不会影响默认皮肤

**Comment by yujiang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thank u, 明白了。
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yu.jiang.163
                            
                    
                        
                            
                                    yu.jiang.163@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年6月19日 14:02，Ouga<notifications@github.com> 写道： 




可以通过右键->转换皮肤为内嵌皮肤，如果转换成内嵌皮肤双击后会直接编辑内嵌皮肤，不会影响默认皮肤



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
