### ISSUE TITLE
点击某个元素导致该元素从一个Group飞到另一个Group

### ISSUE THREAD

**Issue by zhumxiang** [egret-labs/egret-ui-editor-opensource#79]
拖拽操作缺少一个起码的鼠标最小移动距离阈值

**Comment by fpsqdb** [comment]
@zhumxiang 能提供一个示例吗，我们这无法复现，示例能帮助我们定位是bug还是设计缺陷

**Comment by zhumxiang** [comment]
> @zhumxiang 能提供一个示例吗，我们这无法复现，示例能帮助我们定位是bug还是设计缺陷

<?xml version='1.0' encoding='utf-8'?>
<e:Skin class="TestSkin"
	 width="720"
	height="1280" xmlns:e="http://ns.egret.com/eui">
	<e:Group width="200" height="200" x="128" y="388">
		<e:Rect width="200" height="200" x="284" y="82"/>
	</e:Group>
</e:Skin>

点击超出父Group范围的Rect元素，该元素自动跳到skin根节点下

**Comment by fpsqdb** [comment]
使用v1.10.1无法重现，如果要限制在当前Group内移动，请按住Alt键

**Comment by zhumxiang** [comment]
> 使用v1.10.1无法重现，如果要限制在当前Group内移动，请按住Alt键

按alt确实可以，那我提个建议吧，有时候我只想双击某个元素编辑皮肤，结果自动调整了group，非常不习惯，毕竟用wing的时候并没有按alt的习惯，我建议还是判断下鼠标移动距离，不要在明显不想调整ui层级的时候触发调整。

**Comment by fpsqdb** [comment]
右键出现菜单后再左键点击可以重现
