### ISSUE TITLE
在vscode重命名皮肤文件父级文件夹后,无法正常打开被重命名文件夹下exml

### ISSUE THREAD

**Issue by PotentialSteffan** [egret-labs/egret-ui-editor-opensource#89]

**Comment by fpsqdb** [comment]
重启Editor可以打开吗，或者运行egret run项目UI显示正常吗

**Comment by PotentialSteffan** [comment]
> 重启Editor可以打开吗，或者运行egret run项目UI显示正常吗

重启是可以打开的,主要的问题是Editor这边没有同步路径变更

**Comment by fpsqdb** [comment]
输出窗口报的什么错误，我这测试可以，没有重现

**Comment by PotentialSteffan** [comment]
没有报错,在Win10平台,我这边是必现的,ctrl+p选择回车后,闪了一下,分页都没有显示出来
